### ISSUE TITLE
TLS Certificate Files

### ISSUE THREAD

**Issue by canadaduane** [jemmic/docker-janus#1]
Where do the certificate files come from? Are they generated and self-signed?

I'm getting an error when I run `docker-compose up`:

```
[FATAL] [dtls.c:janus_dtls_load_keys:290] Error opening certificate file
```

I see the `janus.jcfg` file contains the following configuration:
```
certificates: {
        cert_pem = "/opt/janus/share/janus/certs/mycert.pem"
        cert_key = "/opt/janus/share/janus/certs/mycert.key"
        #cert_pwd = "secretpassphrase"
}
```

But when I run `docker run -it jemmic/docker-janis /bin/bash` and poke around in `/opt/janus/share/janus/` there is no `certs` directory.

What am I missing?

Thanks!

**Comment by pyarmak** [comment]
@canadaduane You should just comment out those two cert lines in the config unless you want to provide your own certificates. 
Janus autogenerates certificates now if they are missing on startup. See: https://groups.google.com/forum/#!topic/meetecho-janus/348-CzdcZxM

**Comment by canadaduane** [comment]
I can't recall if I tried commenting those lines out. I ended up creating my own cert and just putting it in the appointed location.

**Comment by christophe-kamphaus-jemmic** [comment]
I always mount my own certificates and customized config files as such the included config files are more of a template to get started with.
