### ISSUE TITLE
Git SHA of usrsctp not available

### ISSUE THREAD

**Issue by canadaduane** [jemmic/docker-janus#2]
I'm not sure why this is the case, but the default commit SHA for usrsctp is not considered a "tree" by git.

When I enable `JANUS_WITH_DATACHANNELS` I get an error:

```
Cloning into '/usr/local/src/usrsctp'...
fatal: reference is not a tree: c5abb7a4e65449e32c33fa7703a7bc234bdffb82
```

I recommend changing `JANUS_USRSCTP_VERSION` in the Dockerfile as follows:

```
ARG JANUS_USRSCTP_VERSION="1e15794b1d8d3d16047ccc2826ab2d24745d39e4"
```

(i.e. a recent commit)

**Comment by christophe-kamphaus-jemmic** [comment]
This is fixed with the merging of https://github.com/jemmic/docker-janus/pull/3
